### ISSUE TITLE
Allow other file extensions than zip

### ISSUE THREAD

**Issue by cxcandid** [sozip/sozip-spec#7]
It would be nice if we could store a Geopackage database inside a SOZIP-compressed .qgz file. At the moment it's not allowed, because /vsizip/ refuses to open the datasource, if the file extension is different than .zip. My intension is to store the QGIS project file together with the GPKG data.

**Comment by rouault** [comment]
> /vsizip/ refuses to open the datasource, if the file extension is different than .zip.

actually, you can open a zip file with any extension. Cf https://gdal.org/user/virtual_file_systems.html#vsizip-zip-archives :
"an alternate syntax is available so as to enable chaining and not being dependent on .zip extension, e.g.: /vsizip/{/path/to/the/archive}/path/inside/the/zip/file. Note that /path/to/the/archive may also itself use this alternate syntax."

**Comment by cxcandid** [comment]
Wow Even, I have never received such a quick response! thanx a lot 😀

**Comment by cxcandid** [comment]
Unfortunately `ogrinfo` and `QGIS` refuse to open a SOZIP datasource inside a `.qgz` file (Windows 10).
If I rename the file extension to `.zip` everything works like expected.

```
ogrinfo "/vsizip/c:\data\myproject.qgz\myproject.gpkg"
```
QGIS ogr datasource URI:
```
/vsizip/c:/data/myproject.qgz/myproject.gpkg|layername=test
```

**Comment by rouault** [comment]
you need to use the curl brackets { }
```
ogrinfo "/vsizip/{c:\data\myproject.qgz}/myproject.gpkg"
```

**Comment by cxcandid** [comment]
Arrgg ... totally missed the brackets ... thanx again!

This is really cool ... even works with relative paths (i.e. "/vsizip/{./myproject.qgz}/pyproject.gpkg|layername=test")
